import type { Metadata } from "next";
import localFont from "next/font/local";
// import BootstrapClient from '@/components/BootstrapClient.js';
import Script from "next/script";

import 'bootstrap/dist/css/bootstrap.css';
import "./globals.css";
import "../assets/css/font-awesome-all.css" ;
import "../assets/css/flaticon.css" ;
import "../assets/css/owl.css" ;
import "../assets/css/bootstrap.css" ;
import "../assets/css/jquery.fancybox.min.css" ;
import "../assets/css/animate.css" ;
import "../assets/css/nice-select.css" ;
import "../assets/css/color.css" ;
import "../assets/css/style.css" ;
import "../assets/css/responsive.css" ;



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
            <Script  src="/assets/js/jquery.js" />
      <Script  src="assets/js/jquery.js" />
    <Script  src="/assets/js/popper.min.js" />
    <Script  src="/assets/js/bootstrap.min.js" />
    <Script  src="/assets/js/owl.js" />
    <Script  src="/assets/js/wow.js" />
    <Script  src="/assets/js/validation.js" />
    <Script  src="/assets/js/jquery.fancybox.js" />
    <Script  src="/assets/js/appear.js" />
    <Script  src="/assets/js/scrollbar.js" />
    <Script  src="/assets/js/jquery.nice-select.min.js" />
    <Script  src="/assets/js/isotope.js" />


    <Script  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA-CE0deH3Jhj6GN4YvdCFZS7DpbXexzGU" />
    <Script  src="/assets/js/gmaps.js" />
    <Script  src="/assets/js/map-helper.js" />


    <Script  src="/assets/js/script.js" />
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        {/* <BootstrapClient /> */}
      </body>

    </html>
  );
}


